In [1]:
import pandas as pd

In [63]:
# Reading csv file
df = pd.read_csv(
    r'C:\Users\Mateo Alvarez\OneDrive\Documentos\DATASET_FACTORY\output\Movimientos_Almacen\mining_warehouse_movements.csv',
    sep=';',
)

In [11]:
# Accediendo al tamaño de los axis
df.shape

(129093, 38)

In [12]:
# Obteniendo acceso a los indices
df.index

RangeIndex(start=0, stop=129093, step=1)

In [13]:
# Accediendo al atributo columns
df.columns

Index(['movement_id', 'movement_date', 'year', 'month', 'day_of_week',
       'movement_type', 'movement_direction', 'reference_type', 'reference_id',
       'mine_id', 'mine_name', 'mine_province', 'mine_commodity',
       'warehouse_id', 'warehouse_name', 'warehouse_type',
       'warehouse_province', 'related_warehouse_id', 'material_id', 'category',
       'subcategory', 'criticality', 'abc_class', 'unit_of_measure',
       'supplier_id', 'supplier_country', 'supplier_type', 'quantity',
       'unit_cost_usd', 'total_value_usd', 'stock_before', 'stock_after',
       'requesting_area', 'adjustment_reason', 'promised_date',
       'actual_receipt_date', 'delay_days', 'user_role'],
      dtype='str')

In [14]:
#Tipo de dato de cada columna
df.dtypes

movement_id                 str
movement_date               str
year                      int64
month                     int64
day_of_week                 str
movement_type               str
movement_direction          str
reference_type              str
reference_id                str
mine_id                     str
mine_name                   str
mine_province               str
mine_commodity              str
warehouse_id                str
warehouse_name              str
warehouse_type              str
warehouse_province          str
related_warehouse_id        str
material_id                 str
category                    str
subcategory                 str
criticality                 str
abc_class                   str
unit_of_measure             str
supplier_id                 str
supplier_country            str
supplier_type               str
quantity                  int64
unit_cost_usd           float64
total_value_usd         float64
stock_before              int64
stock_after               int64
requesting_area             str
adjustment_reason           str
promised_date               str
actual_receipt_date         str
delay_days              float64
user_role                   str
dtype: object

In [16]:
# Mostrando Info del Dataframev  -> Podemos ver si hay valores NaN o no 
df.info

<bound method DataFrame.info of         movement_id movement_date  year  month day_of_week  \
0       MOV-0000001     2/10/2023  2023     10       Lunes
1       MOV-0000002     2/10/2023  2023     10       Lunes
2       MOV-0000003     2/10/2023  2023     10       Lunes
3       MOV-0000004     2/10/2023  2023     10       Lunes
4       MOV-0000005     2/10/2023  2023     10       Lunes
...             ...           ...   ...    ...         ...
129088  MOV-0129089     14/9/2026  2026      9       Lunes
129089  MOV-0129090     14/9/2026  2026      9       Lunes
129090  MOV-0129091     14/9/2026  2026      9       Lunes
129091  MOV-0129092     14/9/2026  2026      9       Lunes
129092  MOV-0129093     14/9/2026  2026      9       Lunes

                movement_type movement_direction          reference_type  \
0        Transferencia Salida             Salida  Orden de Transferencia
1             Despacho a Mina             Salida          Pedido de Mina
2             Despacho a Mina             Salida          Pedido de Mina
3             Despacho a Mina             Salida          Pedido de Mina
4             Despacho a Mina             Salida          Pedido de Mina
...                       ...                ...                     ...
129088        Despacho a Mina             Salida          Pedido de Mina
129089        Despacho a Mina             Salida          Pedido de Mina
129090  Transferencia Entrada            Entrada  Orden de Transferencia
129091   Transferencia Salida             Salida  Orden de Transferencia
129092        Despacho a Mina             Salida          Pedido de Mina

         reference_id  mine_id  ... unit_cost_usd total_value_usd  \
0       TR-00004-0000      NaN  ...         13.80          427.80
1       WO-00009-0000  MIN-001  ...        123.20          985.60
2       WO-00020-0000  MIN-002  ...        879.44         1758.88
3       WO-00025-0000  MIN-004  ...        101.84          611.04
4       WO-00026-0000  MIN-007  ...         97.91          195.82
...               ...      ...  ...           ...             ...
129088  WO-00509-0154  MIN-004  ...         22.98           22.98
129089  WO-00514-0154  MIN-002  ...         42.30           42.30
129090  TR-00515-0153  MIN-005  ...          7.80          335.40
129091  TR-00518-0154      NaN  ...         45.69         1370.70
129092  WO-00519-0154  MIN-005  ...          4.88           48.80

       stock_before stock_after         requesting_area adjustment_reason  \
0               143         112                     NaN               NaN
1                17           9     Seguridad e Higiene               NaN
2                 2           0     Seguridad e Higiene               NaN
3                13           7       Logística Interna               NaN
4                 3           1     Seguridad e Higiene               NaN
...             ...         ...                     ...               ...
129088            1           0  Perforación y Voladura               NaN
129089            2           1  Perforación y Voladura               NaN
129090           27          70                     NaN               NaN
129091           79          49                     NaN               NaN
129092           21          11      Mantenimiento Mina               NaN

       promised_date actual_receipt_date delay_days               user_role
0                NaN                 NaN        NaN  Jefe de Abastecimiento
1                NaN                 NaN        NaN  Jefe de Abastecimiento
2                NaN                 NaN        NaN  Jefe de Abastecimiento
3                NaN                 NaN        NaN  Analista de Inventario
4                NaN                 NaN        NaN  Jefe de Abastecimiento
...              ...                 ...        ...                     ...
129088           NaN                 NaN        NaN              Almacenero
129089           NaN                 NaN        NaN  Jefe de Abastecimiento
129090           NaN           14/9/2026        NaN  Jefe de Abastecimiento
129091           NaN                 NaN        NaN  Analista de Inventario
129092           NaN                 NaN        NaN   Supervisor de Almacén

[129093 rows x 38 columns]>

In [18]:
# Devuelve valores estadisticos del data frame
df.describe()

,year,month,quantity,unit_cost_usd,total_value_usd,stock_before,stock_after,delay_days
count,129093.000000,129093.000000,129093.000000,129093.000000,129093.000000,129093.000000,129093.000000,24790.000000
mean,2024.732759,6.472954,23.019986,1388.048199,3662.775692,37.425716,37.334364,6.325978
std,0.913197,3.469021,40.274099,5103.122799,7132.748320,76.568915,76.383109,4.879535
min,2023.000000,1.000000,1.000000,3.180000,3.180000,0.000000,0.000000,-43.000000
25%,2024.000000,3.000000,3.000000,25.050000,341.340000,3.000000,3.000000,3.000000
50%,2025.000000,6.000000,8.000000,127.980000,1228.500000,12.000000,12.000000,8.000000
75%,2025.000000,10.000000,24.000000,536.350000,3823.360000,34.000000,34.000000,10.000000
max,2026.000000,12.000000,574.000000,81247.860000,132475.030000,1475.000000,1224.000000,65.000000

In [21]:
# Tamaño del dataframe
len(df)

129093

In [26]:
# Indice maximo del dataframe
max(df.index)

129092

In [27]:
# Indice minimo del dataframe
min(df.index)

0

In [28]:
# Obtener el Tipo de Dato}
type(df)

pandas.DataFrame

In [31]:
# Redondear valores del dataframe
round(df,2)

,movement_id,movement_date,year,month,day_of_week,movement_type,movement_direction,reference_type,reference_id,mine_id,...,unit_cost_usd,total_value_usd,stock_before,stock_after,requesting_area,adjustment_reason,promised_date,actual_receipt_date,delay_days,user_role
0,MOV-0000001,2/10/2023,2023,10,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00004-0000,NaN,...,13.80,427.80,143,112,NaN,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
1,MOV-0000002,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00009-0000,MIN-001,...,123.20,985.60,17,9,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
2,MOV-0000003,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00020-0000,MIN-002,...,879.44,1758.88,2,0,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
3,MOV-0000004,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00025-0000,MIN-004,...,101.84,611.04,13,7,Logística Interna,NaN,NaN,NaN,NaN,Analista de Inventario
4,MOV-0000005,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00026-0000,MIN-007,...,97.91,195.82,3,1,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129088,MOV-0129089,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00509-0154,MIN-004,...,22.98,22.98,1,0,Perforación y Voladura,NaN,NaN,NaN,NaN,Almacenero
129089,MOV-0129090,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00514-0154,MIN-002,...,42.30,42.30,2,1,Perforación y Voladura,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
129090,MOV-0129091,14/9/2026,2026,9,Lunes,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00515-0153,MIN-005,...,7.80,335.40,27,70,NaN,NaN,NaN,14/9/2026,NaN,Jefe de Abastecimiento
129091,MOV-0129092,14/9/2026,2026,9,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00518-0154,NaN,...,45.69,1370.70,79,49,NaN,NaN,NaN,NaN,NaN,Analista de Inventario
129092,MOV-0129093,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00519-0154,MIN-005,...,4.88,48.80,21,11,Mantenimiento Mina,NaN,NaN,NaN,NaN,Supervisor de Almacén

In [46]:
# Seleccionar Una Columna/Serie del dataframe
df['movement_type']

0          Transferencia Salida
1               Despacho a Mina
2               Despacho a Mina
3               Despacho a Mina
4               Despacho a Mina
                  ...
129088          Despacho a Mina
129089          Despacho a Mina
129090    Transferencia Entrada
129091     Transferencia Salida
129092          Despacho a Mina
Name: movement_type, Length: 129093, dtype: str

In [47]:
# Revisar tipo de data de la Columna/Serie
type(df['movement_type'])

pandas.Series

In [48]:
# Series: atributos y metodos
df['movement_type'].index

RangeIndex(start=0, stop=129093, step=1)

In [52]:
df['movement_type'].head(5 )

0    Transferencia Salida
1         Despacho a Mina
2         Despacho a Mina
3         Despacho a Mina
4         Despacho a Mina
Name: movement_type, dtype: str

In [56]:
# Seleccionar dos 
df[['movement_id','movement_type']]

        movement_id          movement_type
0       MOV-0000001   Transferencia Salida
1       MOV-0000002        Despacho a Mina
2       MOV-0000003        Despacho a Mina
3       MOV-0000004        Despacho a Mina
4       MOV-0000005        Despacho a Mina
...             ...                    ...
129088  MOV-0129089        Despacho a Mina
129089  MOV-0129090        Despacho a Mina
129090  MOV-0129091  Transferencia Entrada
129091  MOV-0129092   Transferencia Salida
129092  MOV-0129093        Despacho a Mina

[129093 rows x 2 columns]

In [68]:
# Seleccionar dos o mas columnas
df[['movement_id','movement_type','reference_type','mine_id']]

        movement_id          movement_type          reference_type  mine_id
0       MOV-0000001   Transferencia Salida  Orden de Transferencia      NaN
1       MOV-0000002        Despacho a Mina          Pedido de Mina  MIN-001
2       MOV-0000003        Despacho a Mina          Pedido de Mina  MIN-002
3       MOV-0000004        Despacho a Mina          Pedido de Mina  MIN-004
4       MOV-0000005        Despacho a Mina          Pedido de Mina  MIN-007
...             ...                    ...                     ...      ...
129088  MOV-0129089        Despacho a Mina          Pedido de Mina  MIN-004
129089  MOV-0129090        Despacho a Mina          Pedido de Mina  MIN-002
129090  MOV-0129091  Transferencia Entrada  Orden de Transferencia  MIN-005
129091  MOV-0129092   Transferencia Salida  Orden de Transferencia      NaN
129092  MOV-0129093        Despacho a Mina          Pedido de Mina  MIN-005

[129093 rows x 4 columns]

In [76]:
# Agregar una nueva columna al dataframe
df['calidad_material'] = 'Buena'

In [97]:
# Agregar una nueva columna con Array
import numpy as np
array = np.arange(0,129093)

df['coords'] = array

In [101]:
# OPERACIONES CON DATAFRAMES
# Selecciona una columna y calcula la suma total
df['unit_cost_usd'].sum()

np.float64(179187306.13)

In [104]:
# Cantidad de Filas
df['unit_cost_usd'].count()

np.float64(1388.0481988179065)

In [105]:
# Promedios
df['unit_cost_usd'].mean()# Promedios

np.float64(1388.0481988179065)

In [106]:
#Divison Estandar
df['unit_cost_usd'].std()

np.float64(5103.122799176936)

In [107]:
# Maximo y Minimo
df['unit_cost_usd'].min()
df['unit_cost_usd'].max()

np.float64(81247.86)

In [108]:
# Calcular mas rapido con .describe
df.describe()

,year,month,quantity,unit_cost_usd,total_value_usd,stock_before,stock_after,delay_days,coords
count,129093.000000,129093.000000,129093.000000,129093.000000,129093.000000,129093.000000,129093.000000,24790.000000,129093.000000
mean,2024.732759,6.472954,23.019986,1388.048199,3662.775692,37.425716,37.334364,6.325978,64546.000000
std,0.913197,3.469021,40.274099,5103.122799,7132.748320,76.568915,76.383109,4.879535,37266.083488
min,2023.000000,1.000000,1.000000,3.180000,3.180000,0.000000,0.000000,-43.000000,0.000000
25%,2024.000000,3.000000,3.000000,25.050000,341.340000,3.000000,3.000000,3.000000,32273.000000
50%,2025.000000,6.000000,8.000000,127.980000,1228.500000,12.000000,12.000000,8.000000,64546.000000
75%,2025.000000,10.000000,24.000000,536.350000,3823.360000,34.000000,34.000000,10.000000,96819.000000
max,2026.000000,12.000000,574.000000,81247.860000,132475.030000,1475.000000,1224.000000,65.000000,129092.000000

In [117]:
df[['unit_cost_usd','total_value_usd']]

        unit_cost_usd  total_value_usd
0               13.80           427.80
1              123.20           985.60
2              879.44          1758.88
3              101.84           611.04
4               97.91           195.82
...               ...              ...
129088          22.98            22.98
129089          42.30            42.30
129090           7.80           335.40
129091          45.69          1370.70
129092           4.88            48.80

[129093 rows x 2 columns]

In [114]:
# Calcular Suma Para FILAS
df['total_value_usd'] + df['unit_cost_usd']

0          441.60
1         1108.80
2         2638.32
3          712.88
4          293.73
           ...
129088      45.96
129089      84.60
129090     343.20
129091    1416.39
129092      53.68
Length: 129093, dtype: float64

In [118]:
# METODO VALUE COUNTS