# Ordenar un Dataframe

In [1]:
import pandas as pd

In [4]:

df = pd.read_csv(r'C:\Users\Mateo Alvarez\OneDrive\Documentos\DATASET_FACTORY\output\Movimientos_Almacen\mining_warehouse_movements.csv',
    sep=';',)
df

,movement_id,movement_date,year,month,day_of_week,movement_type,movement_direction,reference_type,reference_id,mine_id,...,unit_cost_usd,total_value_usd,stock_before,stock_after,requesting_area,adjustment_reason,promised_date,actual_receipt_date,delay_days,user_role
0,MOV-0000001,2/10/2023,2023,10,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00004-0000,NaN,...,13.80,427.80,143,112,NaN,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
1,MOV-0000002,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00009-0000,MIN-001,...,123.20,985.60,17,9,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
2,MOV-0000003,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00020-0000,MIN-002,...,879.44,1758.88,2,0,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
3,MOV-0000004,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00025-0000,MIN-004,...,101.84,611.04,13,7,Logística Interna,NaN,NaN,NaN,NaN,Analista de Inventario
4,MOV-0000005,2/10/2023,2023,10,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00026-0000,MIN-007,...,97.91,195.82,3,1,Seguridad e Higiene,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129088,MOV-0129089,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00509-0154,MIN-004,...,22.98,22.98,1,0,Perforación y Voladura,NaN,NaN,NaN,NaN,Almacenero
129089,MOV-0129090,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00514-0154,MIN-002,...,42.30,42.30,2,1,Perforación y Voladura,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
129090,MOV-0129091,14/9/2026,2026,9,Lunes,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00515-0153,MIN-005,...,7.80,335.40,27,70,NaN,NaN,NaN,14/9/2026,NaN,Jefe de Abastecimiento
129091,MOV-0129092,14/9/2026,2026,9,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00518-0154,NaN,...,45.69,1370.70,79,49,NaN,NaN,NaN,NaN,NaN,Analista de Inventario
129092,MOV-0129093,14/9/2026,2026,9,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00519-0154,MIN-005,...,4.88,48.80,21,11,Mantenimiento Mina,NaN,NaN,NaN,NaN,Supervisor de Almacén

In [10]:
    df.sort_values('month',ascending=False)

,movement_id,movement_date,year,month,day_of_week,movement_type,movement_direction,reference_type,reference_id,mine_id,...,unit_cost_usd,total_value_usd,stock_before,stock_after,requesting_area,adjustment_reason,promised_date,actual_receipt_date,delay_days,user_role
50745,MOV-0050746,1/12/2024,2024,12,Domingo,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00008-0060,MIN-004,...,191.54,2106.94,15,26,NaN,NaN,NaN,1/12/2024,NaN,Supervisor de Almacén
50746,MOV-0050747,1/12/2024,2024,12,Domingo,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00015-0060,MIN-003,...,263.70,263.70,1,2,NaN,NaN,NaN,1/12/2024,NaN,Supervisor de Almacén
50747,MOV-0050748,1/12/2024,2024,12,Domingo,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00030-0060,MIN-007,...,4.74,123.24,4,30,NaN,NaN,NaN,1/12/2024,NaN,Almacenero
50748,MOV-0050749,1/12/2024,2024,12,Domingo,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00082-0060,MIN-001,...,4212.64,4212.64,1,2,NaN,NaN,NaN,1/12/2024,NaN,Almacenero
50749,MOV-0050750,1/12/2024,2024,12,Domingo,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00098-0060,MIN-005,...,154.05,770.25,1,6,NaN,NaN,NaN,1/12/2024,NaN,Analista de Inventario
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13802,MOV-0013803,26/1/2024,2024,1,Viernes,Transferencia Salida,Salida,Orden de Transferencia,TR-00208-0016,NaN,...,4620.17,4620.17,2,1,NaN,NaN,NaN,NaN,NaN,Almacenero
13803,MOV-0013804,26/1/2024,2024,1,Viernes,Transferencia Salida,Salida,Orden de Transferencia,TR-00209-0016,NaN,...,234.98,4464.62,85,66,NaN,NaN,NaN,NaN,NaN,Analista de Inventario
13804,MOV-0013805,26/1/2024,2024,1,Viernes,Recepción de Compra,Entrada,Orden de Compra,PO-00212-0016,NaN,...,6332.91,12665.82,0,2,NaN,NaN,15/1/2024,26/1/2024,11.0,Almacenero
13805,MOV-0013806,26/1/2024,2024,1,Viernes,Recepción de Compra,Entrada,Orden de Compra,PO-00214-0016,NaN,...,347.06,9023.56,0,26,NaN,NaN,15/1/2024,26/1/2024,11.0,Jefe de Abastecimiento
55379,MOV-0055380,8/1/2025,2025,1,Miércoles,Recepción de Compra,Entrada,Orden de Compra,PO-00023-0060,MIN-004,...,3374.66,6749.32,0,2,NaN,NaN,9/1/2025,8/1/2025,-1.0,Jefe de Abastecimiento

In [13]:
# Ordenar por multiples columnnas
df.sort_values(['month','year'],ascending=True)

,movement_id,movement_date,year,month,day_of_week,movement_type,movement_direction,reference_type,reference_id,mine_id,...,unit_cost_usd,total_value_usd,stock_before,stock_after,requesting_area,adjustment_reason,promised_date,actual_receipt_date,delay_days,user_role
10568,MOV-0010569,1/1/2024,2024,1,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00002-0013,MIN-007,...,27.47,521.93,40,21,Logística Interna,NaN,NaN,NaN,NaN,Almacenero
10569,MOV-0010570,1/1/2024,2024,1,Lunes,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00004-0012,MIN-005,...,13.80,621.00,3,48,NaN,NaN,NaN,1/1/2024,NaN,Almacenero
10570,MOV-0010571,1/1/2024,2024,1,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00007-0013,NaN,...,79.55,4295.70,82,28,NaN,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
10571,MOV-0010572,1/1/2024,2024,1,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00014-0013,NaN,...,4488.28,26929.68,19,13,NaN,NaN,NaN,NaN,NaN,Analista de Inventario
10572,MOV-0010573,1/1/2024,2024,1,Lunes,Recepción de Compra,Entrada,Orden de Compra,PO-00016-0013,NaN,...,10.75,4730.00,301,741,NaN,NaN,25/12/2023,1/1/2024,7.0,Almacenero
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98469,MOV-0098470,31/12/2025,2025,12,Miércoles,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00510-0116,MIN-005,...,143.12,1717.44,0,12,NaN,NaN,NaN,31/12/2025,NaN,Jefe de Abastecimiento
98470,MOV-0098471,31/12/2025,2025,12,Miércoles,Transferencia Salida,Salida,Orden de Transferencia,TR-00512-0117,NaN,...,202.38,7488.06,44,7,NaN,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
98471,MOV-0098472,31/12/2025,2025,12,Miércoles,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00514-0116,MIN-002,...,42.30,126.90,0,3,NaN,NaN,NaN,31/12/2025,NaN,Supervisor de Almacén
98472,MOV-0098473,31/12/2025,2025,12,Miércoles,Recepción de Compra,Entrada,Orden de Compra,PO-00514-0117,NaN,...,42.30,126.90,1,4,NaN,NaN,22/12/2025,31/12/2025,9.0,Analista de Inventario
98473,MOV-0098474,31/12/2025,2025,12,Miércoles,Despacho a Mina,Salida,Pedido de Mina,WO-00519-0117,MIN-005,...,4.88,58.56,16,4,Mantenimiento Planta,NaN,NaN,NaN,NaN,Supervisor de Almacén

In [15]:
# Ordenar por multiples columnnas Y actualizar en el DF
df.sort_values(['month','year'],ascending=True, inplace=True)
df

,movement_id,movement_date,year,month,day_of_week,movement_type,movement_direction,reference_type,reference_id,mine_id,...,unit_cost_usd,total_value_usd,stock_before,stock_after,requesting_area,adjustment_reason,promised_date,actual_receipt_date,delay_days,user_role
10568,MOV-0010569,1/1/2024,2024,1,Lunes,Despacho a Mina,Salida,Pedido de Mina,WO-00002-0013,MIN-007,...,27.47,521.93,40,21,Logística Interna,NaN,NaN,NaN,NaN,Almacenero
10569,MOV-0010570,1/1/2024,2024,1,Lunes,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00004-0012,MIN-005,...,13.80,621.00,3,48,NaN,NaN,NaN,1/1/2024,NaN,Almacenero
10570,MOV-0010571,1/1/2024,2024,1,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00007-0013,NaN,...,79.55,4295.70,82,28,NaN,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
10571,MOV-0010572,1/1/2024,2024,1,Lunes,Transferencia Salida,Salida,Orden de Transferencia,TR-00014-0013,NaN,...,4488.28,26929.68,19,13,NaN,NaN,NaN,NaN,NaN,Analista de Inventario
10572,MOV-0010573,1/1/2024,2024,1,Lunes,Recepción de Compra,Entrada,Orden de Compra,PO-00016-0013,NaN,...,10.75,4730.00,301,741,NaN,NaN,25/12/2023,1/1/2024,7.0,Almacenero
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98469,MOV-0098470,31/12/2025,2025,12,Miércoles,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00510-0116,MIN-005,...,143.12,1717.44,0,12,NaN,NaN,NaN,31/12/2025,NaN,Jefe de Abastecimiento
98470,MOV-0098471,31/12/2025,2025,12,Miércoles,Transferencia Salida,Salida,Orden de Transferencia,TR-00512-0117,NaN,...,202.38,7488.06,44,7,NaN,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
98471,MOV-0098472,31/12/2025,2025,12,Miércoles,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00514-0116,MIN-002,...,42.30,126.90,0,3,NaN,NaN,NaN,31/12/2025,NaN,Supervisor de Almacén
98472,MOV-0098473,31/12/2025,2025,12,Miércoles,Recepción de Compra,Entrada,Orden de Compra,PO-00514-0117,NaN,...,42.30,126.90,1,4,NaN,NaN,22/12/2025,31/12/2025,9.0,Analista de Inventario
98473,MOV-0098474,31/12/2025,2025,12,Miércoles,Despacho a Mina,Salida,Pedido de Mina,WO-00519-0117,MIN-005,...,4.88,58.56,16,4,Mantenimiento Planta,NaN,NaN,NaN,NaN,Supervisor de Almacén

In [28]:
# Ordenar con funcion KEY
df.sort_values( ['day_of_week'] , ascending=True, key=lambda col:col.str.lower())

,movement_id,movement_date,year,month,day_of_week,movement_type,movement_direction,reference_type,reference_id,mine_id,...,unit_cost_usd,total_value_usd,stock_before,stock_after,requesting_area,adjustment_reason,promised_date,actual_receipt_date,delay_days,user_role
11398,MOV-0011399,7/1/2024,2024,1,Domingo,Recepción de Compra,Entrada,Orden de Compra,PO-00006-0013,MIN-003,...,258.71,1810.97,2,9,NaN,NaN,15/1/2024,7/1/2024,-8.0,Almacenero
11399,MOV-0011400,7/1/2024,2024,1,Domingo,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00014-0013,MIN-007,...,4488.28,26929.68,3,9,NaN,NaN,NaN,7/1/2024,NaN,Analista de Inventario
11400,MOV-0011401,7/1/2024,2024,1,Domingo,Recepción de Compra,Entrada,Orden de Compra,PO-00019-0012,MIN-003,...,19.44,3188.16,87,251,NaN,NaN,6/1/2024,7/1/2024,1.0,Almacenero
11401,MOV-0011402,7/1/2024,2024,1,Domingo,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00042-0013,MIN-004,...,395.78,1187.34,0,3,NaN,NaN,NaN,7/1/2024,NaN,Jefe de Abastecimiento
11402,MOV-0011403,7/1/2024,2024,1,Domingo,Transferencia Entrada,Entrada,Orden de Transferencia,TR-00065-0013,MIN-001,...,51.04,4899.84,60,156,NaN,NaN,NaN,7/1/2024,NaN,Analista de Inventario
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97936,MOV-0097937,26/12/2025,2025,12,Viernes,Despacho a Mina,Salida,Pedido de Mina,WO-00501-0116,MIN-002,...,9.03,117.39,26,13,Operaciones Mina,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
97937,MOV-0097938,26/12/2025,2025,12,Viernes,Transferencia Salida,Salida,Orden de Transferencia,TR-00510-0116,NaN,...,143.12,1717.44,18,6,NaN,NaN,NaN,NaN,NaN,Analista de Inventario
97938,MOV-0097939,26/12/2025,2025,12,Viernes,Transferencia Salida,Salida,Orden de Transferencia,TR-00514-0116,NaN,...,42.30,126.90,4,1,NaN,NaN,NaN,NaN,NaN,Analista de Inventario
97939,MOV-0097940,26/12/2025,2025,12,Viernes,Despacho a Mina,Salida,Pedido de Mina,WO-00515-0116,MIN-005,...,7.80,226.20,70,41,Logística Interna,NaN,NaN,NaN,NaN,Jefe de Abastecimiento
97940,MOV-0097941,26/12/2025,2025,12,Viernes,Despacho a Mina,Salida,Pedido de Mina,WO-00518-0116,MIN-004,...,45.69,731.04,18,2,Perforación y Voladura,NaN,NaN,NaN,NaN,Jefe de Abastecimiento